export interface Word {
  id: number;
  hebrew: string;
  hebrewWithVowels: string;
  arabic: string;
  pronunciation: string;
  category: string;
  mnemonic: string;
}

export interface QuizQuestion {
  id: string;
  wordId: number;
  word: Word;
  questionType: 'multiple-choice' | 'spelling' | 'arabic-to-hebrew';
  questionText: string;
  options: string[];
  correctAnswer: string;
}

export interface MemoryStoryResponse {
  wordId: number;
  story: string; // Dynamic mnemonic story generated by Gemini
  svgCode: string; // SVG cartoon/illustration code generated by Gemini
}
